export interface StorageDriver {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  delete(keys: string[]): Promise<void>;
  /** Public URL for a stored object. */
  url(key: string): string;
}

/** Storage keys are generated by us; still, never let one escape its root. */
export function assertSafeKey(key: string) {
  if (!/^[a-z0-9][a-z0-9/_.-]*$/i.test(key) || key.includes("..")) {
    throw new Error("Invalid storage key");
  }
}
